import type { AgentPlan, AgentPhase, AgentName } from '../types/task.types';
import type { AgentInput, AgentContext, AgentOutput } from '../types/agent.types';
import { saveAgentTask, updateRunStatus } from './agent-memory';

// Import all agents
import { AnalystAgent } from '../agents/analyst.agent';
import { ArchitectAgent } from '../agents/architect.agent';
import { CoderAgent } from '../agents/coder.agent';
import { ReviewerAgent } from '../agents/reviewer.agent';
import { UIUXAgent } from '../agents/uiux.agent';
import { DataAgent } from '../agents/data.agent';
import { IntegrationAgent } from '../agents/integration.agent';

// Progress callback — for SSE streaming to UI
export type ProgressCallback = (event: ProgressEvent) => void;

export interface ProgressEvent {
  runId: number;
  agentName: string;
  status: 'started' | 'done' | 'failed';
  message: string;
  data?: any;
}

// The only agents that actually exist in this system. Used to defend against
// the orchestrator's own LLM occasionally hallucinating a role name it saw
// in the user's own request text (e.g. "DevOps Agent", "Security Agent")
// into the generated plan — without this, one bad name used to crash the
// entire multi-minute run instead of just being skipped.
const KNOWN_AGENTS: AgentName[] = [
  'analyst', 'architect', 'coder', 'reviewer', 'uiux', 'data', 'integration',
];

// Get agent instance by name
function getAgent(name: AgentName, env?: Record<string, string>) {
  switch (name) {
   case 'analyst':     return new AnalystAgent(env);
    case 'architect':   return new ArchitectAgent(env);
    case 'coder':       return new CoderAgent(env);
    case 'reviewer':    return new ReviewerAgent(env);
    case 'uiux':        return new UIUXAgent(env);
    case 'data':        return new DataAgent(env);
    case 'integration': return new IntegrationAgent(env);
    default: throw new Error(`Unknown agent: ${name}`);
  }
}

// Main runner — executes the full agent plan
export async function runAgentPlan(
  plan: AgentPlan,
  onProgress?: ProgressCallback
): Promise<{ context: AgentContext; failures: Array<{ agentName: string; error: string }> }> {

  let context: AgentContext = {};
  // ⚠️ FIX: agent failures were saved to the DB but never bubbled up past
  // this function — the orchestrator had no way to know Coder (or any
  // agent) actually failed, so it silently fell back to boilerplate
  // package.json/index.html and reported "success: true" regardless.
  const failures: Array<{ agentName: string; error: string }> = [];

  await updateRunStatus(plan.runId, 'running', undefined, plan.env);

  // Execute each phase in order
  for (const phase of plan.phases) {
    console.log(`\n🚀 Phase: ${phase.phaseName} [${phase.executionType}]`);

    // ⚠️ FIX: drop any agent name the orchestrator's LLM hallucinated (e.g.
    // it saw "DevOps Agent" mentioned in the user's own request text and
    // put "devops" into the plan) before running this phase — one bad name
    // used to throw "Unknown agent: X" and kill the ENTIRE run partway
    // through, losing every file already generated by earlier phases.
    const validAgents = phase.agents.filter((a: any) => KNOWN_AGENTS.includes(a));
    const droppedAgents = phase.agents.filter((a: any) => !KNOWN_AGENTS.includes(a));
    if (droppedAgents.length > 0) {
      console.warn(`⚠️ Skipping unknown agent(s) in plan: ${droppedAgents.join(', ')}`);
    }

    if (phase.executionType === 'sequential') {
      // Run agents one by one — each gets previous agent's output
      for (const agentName of validAgents) {
        const result = await runSingleAgent(
          agentName,
          plan,
          context,
          onProgress
        );
        context = result.context;
        if (result.failure) failures.push(result.failure);
      }
    } else {
      // Run all agents in this phase simultaneously
      const results = await Promise.allSettled(
        validAgents.map((agentName: any) =>
          runSingleAgent(agentName, plan, context, onProgress)
        )
      );

      // Merge all parallel results into context
      for (const result of results) {
        if (result.status === 'fulfilled') {
          Object.assign(context, result.value.context);
          if (result.value.failure) failures.push(result.value.failure);
        }
      }
    }
  }

  await updateRunStatus(plan.runId, 'done', undefined, plan.env);
  return { context, failures };
}

// Run a single agent and update context
async function runSingleAgent(
  agentName: AgentName,
  plan: AgentPlan,
  context: AgentContext,
  onProgress?: ProgressCallback
): Promise<{ context: AgentContext; failure?: { agentName: string; error: string } }> {

  const agent = getAgent(agentName, plan.env);

  // Notify UI — agent started
  onProgress?.({
    runId: plan.runId,
    agentName,
    status: 'started',
    message: getStartMessage(agentName),
  });

  const input: AgentInput = {
    userRequest: plan.userRequest,
    chatId: plan.chatId,
    runId: plan.runId,
    context,
  };

  const output: AgentOutput = await agent.run(input);

  if (output.success) {
    // Save to DB
    await saveAgentTask(plan.runId, agentName, 'done', input, output.data, undefined, plan.env);

    // Update context with this agent's output
    const updatedContext = updateContext(context, agentName, output.data);

    // Notify UI — agent done
    onProgress?.({
      runId: plan.runId,
      agentName,
      status: 'done',
      message: getDoneMessage(agentName),
      data: output.data,
    });

    return { context: updatedContext };
  } else {
    // Save failure to DB
    await saveAgentTask(plan.runId, agentName, 'failed', input, null, output.error, plan.env);

    // Notify UI — agent failed
    onProgress?.({
      runId: plan.runId,
      agentName,
      status: 'failed',
      message: `${agentName} failed: ${output.error}`,
    });

    // Return unchanged context — other agents continue — but now the
    // failure reason travels back up instead of vanishing here.
    return { context, failure: { agentName, error: output.error || 'Unknown error' } };
  }
}

// Put agent output into right context field
function updateContext(
  context: AgentContext,
  agentName: AgentName,
  data: any
): AgentContext {
  const updated = { ...context };

  switch (agentName) {
    case 'analyst':     updated.requirements = data; break;
    case 'architect':   updated.architecture = data; break;
    case 'coder':       updated.generatedCode = data; break;
    case 'uiux':        updated.designDecisions = data; break;
    case 'reviewer':    updated.reviewFeedback = data; break;
    // ⚠️ FIX: these two cases were missing entirely — data/integration agents'
    // outputs were silently dropped (never stored in context), so
    // orchestrator.ts's file-collection step (which reads
    // context.dataFiles?.dataFiles and context.integrationData?.files) always
    // found undefined, even when both agents ran successfully. Their
    // generated files were computed but never made it into the final output.
    case 'data':        updated.dataFiles = data; break;
    case 'integration':  updated.integrationData = data; break;
  }

  return updated;
}

// Human readable messages for UI
function getStartMessage(agentName: AgentName): string {
  const messages: Record<AgentName, string> = {
    orchestrator: '🧠 Planning your project...',
    analyst:      '🔍 Analyzing requirements...',
    architect:    '📐 Designing file structure...',
    coder:        '💻 Writing code...',
    reviewer:     '🔎 Reviewing code quality...',
    uiux:         '🎨 Applying design decisions...',
    data:         '📦 Generating sample data...',
    integration:  '🔌 Setting up integrations...',
  };
  return messages[agentName] || `Running ${agentName}...`;
}

function getDoneMessage(agentName: AgentName): string {
  const messages: Record<AgentName, string> = {
    orchestrator: '✅ Plan ready',
    analyst:      '✅ Requirements analyzed',
    architect:    '✅ Architecture designed',
    coder:        '✅ Code written',
    reviewer:     '✅ Code reviewed',
    uiux:         '✅ Design applied',
    data:         '✅ Sample data ready',
    integration:  '✅ Integrations configured',
  };
  return messages[agentName] || `✅ ${agentName} done`;
}