import type { Message } from 'ai';
import { useCallback, useEffect, useRef, useState } from 'react';
import { EnhancedStreamingMessageParser } from '~/lib/runtime/enhanced-message-parser';
import { workbenchStore } from '~/lib/stores/workbench';
import { createScopedLogger } from '~/utils/logger';

const logger = createScopedLogger('useMessageParser');

// ⚠️ FIX: deterministic (code-level, not prompt-level) guarantee that the bolt.diy-style
// /api/chat stream can NEVER write real backend/secret files — that's exclusively the
// custom orchestrator agent's (/api/agent) job. The system prompt also instructs the
// model not to (see new-prompt.ts), but an instruction can be missed; this filter can't
// be. NOTE: as of this codebase, the orchestrator agent itself doesn't generate a real
// server (no server/, backend/, database/ folders anywhere in it) — its "backend" work is
// BaaS client integration (Stripe/Firebase/Supabase under src/lib/) + sample data (under
// src/data/) + a real .env (never .env.example, that's just a harmless template). So the
// one thing that actually matters to block here is a real .env file with live secrets —
// the server/backend/database path checks are kept as a forward-looking safety net in
// case a real server ever gets added to the orchestrator later, but they're not doing
// meaningful work today.
function isBackendTerritoryPath(filePath?: string): boolean {
  if (!filePath) return false;

  const normalized = filePath.replace(/^\/+/, '').replace(/^home\/project\//, '');
  const segments = normalized.split('/');
  const topLevelDir = segments.length > 1 ? segments[0].toLowerCase() : '';
  const basename = segments[segments.length - 1].toLowerCase();

  // Real secrets file — never let the chat model write this. `.env.example` (a template
  // with no real values, generated by the integration agent) is explicitly NOT blocked.
  if (basename === '.env' || (/^\.env\./.test(basename) && basename !== '.env.example')) {
    return true;
  }

  // Forward-looking: not currently used by the orchestrator, but kept as a guard in case
  // real server/database code gets added to it later.
  if (['server', 'backend', 'database', 'migrations', 'prisma'].includes(topLevelDir)) {
    return true;
  }
  if (/^server\.(js|ts|mjs|cjs)$/.test(basename)) {
    return true;
  }
  if (basename.endsWith('.sql') || basename === 'schema.prisma') {
    return true;
  }
  return false;
}

// ⚠️ FIX (pre-existing bug, not introduced this session): the constructor of
// EnhancedStreamingMessageParser takes the callbacks object DIRECTLY —
// `constructor(callbacks: ArtifactCallback = {})` — but this call was wrapping them
// in an extra `{ callbacks: {...} } ` layer. That meant `this.callbacks.onArtifactOpen`
// (etc.) was always undefined inside the parser, so every `this.callbacks.onArtifactOpen?.(...)`
// call silently no-op'd — NONE of these callbacks ever fired, for any /api/chat-streamed
// message, ever. That's the real reason generated files never reached workbenchStore via
// the normal chat path (not a timing race — the callbacks flat-out never ran). Only the
// separate orchestrator agent (runAgent(), which writes to WebContainer directly) ever
// actually produced visible files. Removing the extra wrapper layer fixes it.
const messageParser = new EnhancedStreamingMessageParser({
  onArtifactOpen: (data) => {
    logger.trace('onArtifactOpen', data.artifactId);
    workbenchStore.showWorkbench.set(true);
    workbenchStore.addArtifact(data);
  },
  onArtifactClose: (data) => {
    logger.trace('onArtifactClose', data.artifactId);
    workbenchStore.updateArtifact(data, { closed: true });
  },
  onActionOpen: (data) => {
    const actionType = data.type ?? data.action?.type;
    const filePath = data.filePath ?? data.action?.filePath;
    logger.trace('onActionOpen', actionType, filePath);
    if (actionType === 'file') {
      if (isBackendTerritoryPath(filePath)) {
        logger.warn('Blocked backend-territory file from /api/chat stream — this is the orchestrator agent\'s job:', filePath);
        return;
      }
      workbenchStore.addAction(data);
    }
  },
  onActionClose: (data) => {
    const actionType = data.type ?? data.action?.type;
    const filePath = data.filePath ?? data.action?.filePath;
    logger.trace('onActionClose', actionType, filePath);
    if (actionType === 'file' && isBackendTerritoryPath(filePath)) {
      logger.warn('Blocked backend-territory file from /api/chat stream — this is the orchestrator agent\'s job:', filePath);
      return;
    }
    if (actionType !== 'file') {
      workbenchStore.addAction(data);
    }
    workbenchStore.runAction(data);
  },
  onActionStream: (data) => {
    const filePath = data.filePath ?? data.action?.filePath;
    if (isBackendTerritoryPath(filePath)) {
      return;
    }
    logger.trace('onActionStream', data.action);
    workbenchStore.runAction(data, true);
  },
});

const extractTextContent = (message: Message) =>
  Array.isArray(message.content)
    ? (message.content.find((item) => item.type === 'text')?.text as string) || ''
    : (message.content as string);

/**
 * Run a full parse pass over all messages and return the display map.
 * This is extracted so we can call it both from parseMessages and from the
 * isLoading=false forced-flush below.
 */
function runFullParse(messages: Message[]): { [key: number]: string } {
  const result: { [key: number]: string } = {};
  for (const [index, message] of messages.entries()) {
    if (message.role === 'assistant' || message.role === 'user') {
      const raw = extractTextContent(message);
      const parsed = messageParser.parse(message.id, raw);
      // For assistant messages: if parsed is empty but raw exists, show a
      // placeholder so the user knows something was generated (workbench shows it)
      if (message.role === 'assistant' && parsed === '' && raw.includes('<boltArtifact')) {
        result[index] = '\u2009'; // thin space — visible but blank, prevents dots
      } else {
        result[index] = parsed;
      }
    }
  }
  return result;
}

export function useMessageParser() {
  const [parsedMessages, setParsedMessages] = useState<{ [key: number]: string }>({});
  // Keep a ref to the latest messages so we can force-flush after stream ends
  const latestMessagesRef = useRef<Message[]>([]);

  /**
   * parseMessages is called by processSampledMessages which is rate-limited
   * to 50 ms.  That means the FINAL call (isLoading=false) may arrive while
   * the sampler is still cooling down and gets silently dropped.
   *
   * Strategy:
   *   • During streaming  → parse & set immediately (sampler handles throttle)
   *   • When stream ends  → schedule a guaranteed flush via setTimeout(0) so it
   *     runs outside the sampler's cooldown window
   */
  const parseMessages = useCallback((messages: Message[], isLoading: boolean) => {
    latestMessagesRef.current = messages;

    if (!isLoading) {
      // Stream just ended — reset so artifacts re-run their workbench callbacks
      // on the final, complete content.
      messageParser.reset();

      // Defer the final parse slightly so it definitely runs AFTER the sampler
      // cooldown; this guarantees parsedMessages is populated on stream end.
      setTimeout(() => {
        const parsed = runFullParse(latestMessagesRef.current);
        setParsedMessages(parsed);
      }, 0);
    } else {
      // Mid-stream — parse current snapshot and show it
      const parsed = runFullParse(messages);
      setParsedMessages(parsed);
    }
  }, []);

  return { parsedMessages, parseMessages };
}