import { AgentBase } from '../core/agent-base';
import type { AgentInput, AgentOutput } from '../types/agent.types';
import {
  FRONTEND_CODER_SYSTEM_PROMPT,
  FRONTEND_CODER_USER_PROMPT,
  BACKEND_CODER_SYSTEM_PROMPT,
  BACKEND_CODER_USER_PROMPT,
  FRONTEND_FILE_SYSTEM_PROMPT,
  FRONTEND_FILE_USER_PROMPT,
  BACKEND_FILE_SYSTEM_PROMPT,
  BACKEND_FILE_USER_PROMPT,
  buildVersionHintsBlock,
} from '../prompts/coder.prompt';
import { runBuildHeal } from '../core/build-healer';

const BACKEND_PATH_PREFIXES = ['server/', 'backend/', 'database/', 'migrations/'];

function isBackendPath(path: string): boolean {
  const normalized = path.replace(/^\/+/, '');
  return BACKEND_PATH_PREFIXES.some((p) => normalized.startsWith(p)) || normalized.endsWith('.sql');
}

const PER_FILE_TIMEOUT_MS = 150000;

const CONFIG_FILE_BASENAMES = new Set([
  'package.json',
  'vite.config.ts',
  'vite.config.js',
  'vite.config.mjs',
  'tsconfig.json',
  'tsconfig.node.json',
  'postcss.config.js',
  'postcss.config.cjs',
  'tailwind.config.js',
  'tailwind.config.cjs',
  'index.html',
  '.gitignore',
]);

function isConfigFile(path: string): boolean {
  const basename = path.replace(/^\/+/, '').split('/').pop() || '';
  return CONFIG_FILE_BASENAMES.has(basename);
}

function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'app'
  );
}

function buildConfigFileTemplates(requirements: any, architecture: any): Record<string, string> {
  const projectName = slugify(requirements?.projectName || 'digitalsofts-app');
  const displayTitle = requirements?.projectName || 'App';
  const needsBackend =
    (architecture?.apiRoutes && architecture.apiRoutes.length > 0) ||
    (architecture?.databaseSchema && architecture.databaseSchema.length > 0);

  const packageJson = {
    name: projectName,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview',
      ...(needsBackend ? { server: 'node server/index.js' } : {}),
    },
    dependencies: {
      react: '^18.2.0',
      'react-dom': '^18.2.0',
      'react-router-dom': '^6.22.0',
      ...(needsBackend
        ? {
            express: '^4.19.2',
            cors: '^2.8.5',
            dotenv: '^16.4.5',
            // ── Part 2: sql.js replaces pg — pure WASM, works in WebContainer ──
            'sql.js': '^1.12.0',
          }
        : {}),
    },
    devDependencies: {
      '@types/react': '^18.2.66',
      '@types/react-dom': '^18.2.22',
      '@vitejs/plugin-react': '^4.2.1',
      autoprefixer: '^10.4.19',
      postcss: '^8.4.38',
      tailwindcss: '^3.4.3',
      typescript: '^5.4.5',
      vite: '^5.2.0',
    },
  };

  // ── Bug 3 fix: add /api proxy in vite.config when backend is needed ──────────
  const viteConfig = needsBackend
    ? `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      },
    },
  },
});
`
    : `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
  },
});
`;
  // ────────────────────────────────────────────────────────────────────────────

  // ── Part 2: deterministic SQLite initializer — never generated by LLM ──────
  const sqliteDbModule =
    needsBackend && (architecture?.databaseType !== 'non-relational')
      ? `// Auto-generated SQLite initializer — do not edit manually
import initSqlJs from 'sql.js';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const DB_PATH = join(__dir, 'app.sqlite');
const SCHEMA_PATH = join(__dir, 'schema.sql');

let _db = null;

export async function getDb() {
  if (_db) return _db;
  const SQL = await initSqlJs();
  if (existsSync(DB_PATH)) {
    _db = new SQL.Database(readFileSync(DB_PATH));
  } else {
    _db = new SQL.Database();
    if (existsSync(SCHEMA_PATH)) {
      const schema = readFileSync(SCHEMA_PATH, 'utf8');
      _db.run(schema);
    }
    persistDb();
  }
  return _db;
}

export function persistDb() {
  if (!_db) return;
  mkdirSync(dirname(DB_PATH), { recursive: true });
  writeFileSync(DB_PATH, Buffer.from(_db.export()));
}
`
      : null;
  // ────────────────────────────────────────────────────────────────────────────

  return {
    'package.json': JSON.stringify(packageJson, null, 2),
    'vite.config.ts': viteConfig,
    ...(sqliteDbModule ? { 'server/database/db.js': sqliteDbModule } : {}),
    'tsconfig.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2020',
          useDefineForClassFields: true,
          lib: ['ES2020', 'DOM', 'DOM.Iterable'],
          module: 'ESNext',
          skipLibCheck: true,
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: 'react-jsx',
          strict: false,
          noUnusedLocals: false,
          noUnusedParameters: false,
        },
        include: ['src'],
      },
      null,
      2,
    ),
    'postcss.config.js': `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`,
    'tailwind.config.js': `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
};
`,
    'index.html': `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${displayTitle}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
    '.gitignore': `node_modules\ndist\n.env\n.env.local\n`,
  };
}

const ENTRY_FILE_PATTERN = /^src\/main\.(tsx|jsx|ts|js)$/;

const ROUTER_USAGE_PATTERN = /(?:<Link|<Route|<BrowserRouter|<HashRouter|useNavigate|useLocation|useParams|<NavLink)[ >/]/;

function usesRouter(files: Record<string, string>): boolean {
  return Object.values(files).some((content) => ROUTER_USAGE_PATTERN.test(content));
}

const KNOWN_VERSIONS: Record<string, string> = {
  'react-icons': '^5.1.0',
  '@headlessui/react': '^2.1.2',
  '@mui/material': '^5.15.19',
  '@mui/system': '^5.15.19',
  '@mui/icons-material': '^5.15.19',
  '@mui/x-data-grid': '^7.7.1',
  '@mui/x-date-pickers': '^7.7.1',
  '@mui/lab': '^5.0.0-alpha.170',
  '@emotion/react': '^11.11.4',
  '@emotion/styled': '^11.11.5',
  'framer-motion': '^11.1.9',
  'lucide-react': '^0.378.0',
  'date-fns': '^3.6.0',
  'axios': '^1.6.8',
  'zod': '^3.23.8',
  'react-hook-form': '^7.51.4',
  'recharts': '^2.12.7',
  'chart.js': '^4.4.2',
  'react-chartjs-2': '^5.2.0',
  'clsx': '^2.1.1',
  'class-variance-authority': '^0.7.0',
  'tailwind-merge': '^2.3.0',
  '@radix-ui/react-dialog': '^1.1.1',
  '@radix-ui/react-dropdown-menu': '^2.1.1',
  '@radix-ui/react-label': '^2.1.0',
  '@radix-ui/react-slot': '^1.1.0',
  '@radix-ui/react-toast': '^1.2.1',
  'react-toastify': '^10.0.5',
  'react-hot-toast': '^2.4.1',
  'uuid': '^10.0.0',
  'nanoid': '^5.0.7',
  'bcrypt': '^5.1.1',
  'bcryptjs': '^2.4.3',
  'jsonwebtoken': '^9.0.2',
  'socket.io': '^4.7.5',
  'socket.io-client': '^4.7.5',
  'multer': '^1.4.5-lts.1',
  'sharp': '^0.33.3',
  'sql.js': '^1.12.0',
};

// ── 1b: peer dependency map ───────────────────────────────────────────────────
// When a package is detected and added, also add its mandatory peers.
const PEER_DEPS_MAP: Record<string, Record<string, string>> = {
  '@mui/x-data-grid':    { '@mui/material': '^5.15.19', '@mui/system': '^5.15.19', '@emotion/react': '^11.11.4', '@emotion/styled': '^11.11.5' },
  '@mui/x-date-pickers': { '@mui/material': '^5.15.19', '@emotion/react': '^11.11.4', '@emotion/styled': '^11.11.5' },
  '@mui/lab':            { '@mui/material': '^5.15.19', '@emotion/react': '^11.11.4', '@emotion/styled': '^11.11.5' },
  '@mui/icons-material': { '@mui/material': '^5.15.19' },
  'react-chartjs-2':     { 'chart.js': '^4.4.2' },
};

// ── 1b: known-exports guard ───────────────────────────────────────────────────
// Named imports that DO NOT exist in each package — if found, they are crashes.
const INVALID_EXPORTS: Record<string, Set<string>> = {
  'react-data-grid': new Set(['Grid', 'Table', 'Column']),
  '@mui/x-data-grid': new Set(['Grid', 'Table']),
};

// Symbol remap: if an import from package X uses name Y, replace with Z.
const EXPORT_REMAP: Record<string, Record<string, string>> = {
  'react-data-grid': { Grid: 'DataGrid', Table: 'DataGrid', Column: 'GridColDef' },
};

// Bug 1 fix: npm package name validator
const VALID_PKG_RE = /^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/i;
function isValidPackageName(name: string): boolean {
  return (
    VALID_PKG_RE.test(name) &&
    name.length <= 214 &&
    !/\s/.test(name) &&
    !name.includes('..')
  );
}

// ── 1b: React compatibility guard ────────────────────────────────────────────
// react-data-grid v7+ requires React 19. If the project declares React 18 and
// uses react-data-grid, swap it to @mui/x-data-grid + fix all imports.
function guardReactCompatibility(files: Record<string, string>): void {
  if (!files['package.json']) return;
  let pkg: any;
  try { pkg = JSON.parse(files['package.json']); } catch { return; }

  const reactVer: string = pkg.dependencies?.['react'] || pkg.devDependencies?.['react'] || '';
  const isReact18 = reactVer.includes('18');

  if (isReact18 && pkg.dependencies?.['react-data-grid']) {
    console.warn('[Coder] guardReactCompatibility: react-data-grid requires React 19 — swapping to @mui/x-data-grid');
    delete pkg.dependencies['react-data-grid'];
    pkg.dependencies['@mui/x-data-grid'] = KNOWN_VERSIONS['@mui/x-data-grid'];
    pkg.dependencies['@mui/material'] = KNOWN_VERSIONS['@mui/material'];
    pkg.dependencies['@mui/system'] = KNOWN_VERSIONS['@mui/system'];
    pkg.dependencies['@emotion/react'] = KNOWN_VERSIONS['@emotion/react'];
    pkg.dependencies['@emotion/styled'] = KNOWN_VERSIONS['@emotion/styled'];
    files['package.json'] = JSON.stringify(pkg, null, 2);

    // Fix all imports in generated source files
    for (const [fp, content] of Object.entries(files)) {
      if (!/\.(tsx?|jsx?)$/.test(fp)) continue;
      if (!content.includes('react-data-grid')) continue;
      let fixed = content
        .replace(/import\s*\{[^}]*\}\s*from\s*['"]react-data-grid['"];?/g,
          "import { DataGrid } from '@mui/x-data-grid';")
        .replace(/<Grid(\s)/g, '<DataGrid$1')
        .replace(/<Table(\s)/g, '<DataGrid$1')
        .replace(/<\/Grid>/g, '</DataGrid>')
        .replace(/<\/Table>/g, '</DataGrid>');
      files[fp] = fixed;
      console.log(`[Coder] guardReactCompatibility: fixed react-data-grid imports in ${fp}`);
    }
  }
}

function reconcileDependencies(files: Record<string, string>): string[] {
  const warnings: string[] = [];
  const sourceFiles = Object.entries(files).filter(
    ([p]) => /\.(ts|tsx|js|jsx|mjs|cjs)$/.test(p) && p !== 'vite.config.ts' && p !== 'postcss.config.js' && p !== 'tailwind.config.js',
  );

  const detectedPackages = new Set<string>();
  // Bug 1 fix: non-line-crossing import pattern
  const importPattern = /^\s*import\s+(?:[^'"\n]*?\s+from\s+)?['"]([^'"]+)['"]\s*;?\s*$/gm;
  const requirePattern = /require\(['"]((?:@[^/]+\/)?[^/.'"@][^'"]*?)['"]/g;

  for (const [, content] of sourceFiles) {
    let m: RegExpExecArray | null;

    importPattern.lastIndex = 0;
    while ((m = importPattern.exec(content)) !== null) {
      const spec = m[1];
      if (spec.startsWith('.')) continue;
      const pkgName = spec.startsWith('@') ? spec.split('/').slice(0, 2).join('/') : spec.split('/')[0];
      if (pkgName) {
        if (isValidPackageName(pkgName)) {
          detectedPackages.add(pkgName);
        } else {
          const msg = `reconcileDependencies: rejected invalid package candidate "${pkgName}"`;
          console.warn(`[Coder] ${msg}`);
          warnings.push(msg);
        }
      }
    }

    requirePattern.lastIndex = 0;
    while ((m = requirePattern.exec(content)) !== null) {
      const spec = m[1];
      if (spec.startsWith('.')) continue;
      const pkgName = spec.startsWith('@') ? spec.split('/').slice(0, 2).join('/') : spec.split('/')[0];
      if (pkgName) {
        if (isValidPackageName(pkgName)) {
          detectedPackages.add(pkgName);
        } else {
          const msg = `reconcileDependencies: rejected invalid package candidate "${pkgName}"`;
          console.warn(`[Coder] ${msg}`);
          warnings.push(msg);
        }
      }
    }
  }

  if (!files['package.json']) return warnings;
  let pkgJson: any;
  try {
    pkgJson = JSON.parse(files['package.json']);
  } catch {
    return warnings;
  }

  const allDeclared = new Set([
    ...Object.keys(pkgJson.dependencies || {}),
    ...Object.keys(pkgJson.devDependencies || {}),
  ]);

  const SKIP_PREFIXES = ['node:', 'bun:', 'virtual:', 'vite', 'rollup'];
  const NODE_BUILTINS = new Set(['path', 'fs', 'os', 'url', 'http', 'https', 'crypto', 'stream', 'buffer', 'util', 'events', 'child_process', 'readline', 'zlib', 'assert', 'process', 'module', 'perf_hooks', 'async_hooks', 'worker_threads', 'cluster']);

  let injected = 0;
  pkgJson.dependencies = pkgJson.dependencies || {};

  for (const pkg of detectedPackages) {
    if (allDeclared.has(pkg)) continue;
    if (NODE_BUILTINS.has(pkg)) continue;
    if (SKIP_PREFIXES.some((p) => pkg.startsWith(p))) continue;

    const version = KNOWN_VERSIONS[pkg] || '*';
    pkgJson.dependencies[pkg] = version;
    injected++;
    const msg = `reconcileDependencies: added missing dep "${pkg}": "${version}"`;
    console.log(`[Coder] ${msg}`);
    warnings.push(msg);

    const peers = PEER_DEPS_MAP[pkg];
    if (peers) {
      for (const [peer, peerVersion] of Object.entries(peers)) {
        if (!pkgJson.dependencies[peer] && !pkgJson.devDependencies?.[peer]) {
          pkgJson.dependencies[peer] = peerVersion;
          injected++;
          const peerMsg = `reconcileDependencies: added peer dep "${peer}": "${peerVersion}" (required by "${pkg}")`;
          console.log(`[Coder] ${peerMsg}`);
          warnings.push(peerMsg);
        }
      }
    }
  }

  if (injected > 0) {
    files['package.json'] = JSON.stringify(pkgJson, null, 2);
  }

  const NAMED_IMPORT_RE = /import\s*\{([^}]+)\}\s*from\s*['"]((?:@[^/]+\/)?[^/.'"][^'"]*)['"]/g;
  for (const [fp, content] of Object.entries(files)) {
    if (!/\.(tsx?|jsx?)$/.test(fp)) continue;
    let updated = content;
    let fileChanged = false;
    NAMED_IMPORT_RE.lastIndex = 0;
    let m: RegExpExecArray | null;
    while ((m = NAMED_IMPORT_RE.exec(content)) !== null) {
      const importedNames = m[1].split(',').map((s) => s.trim().split(/\s+as\s+/)[0].trim());
      const pkgName = m[2].startsWith('@') ? m[2].split('/').slice(0, 2).join('/') : m[2].split('/')[0];
      const invalids = INVALID_EXPORTS[pkgName];
      const remaps = EXPORT_REMAP[pkgName];
      if (!invalids && !remaps) continue;
      for (const name of importedNames) {
        if (invalids?.has(name)) {
          const replacement = remaps?.[name] || 'DataGrid';
          const msg = `validateNamedImports: "${name}" does not exist in "${pkgName}" — remapping to "${replacement}" in ${fp}`;
          console.warn(`[Coder] ${msg}`);
          warnings.push(msg);
          updated = updated.replace(new RegExp(`\\b${name}\\b`, 'g'), replacement);
          fileChanged = true;
        }
      }
    }
    if (fileChanged) {
      files[fp] = updated;
    }
  }

  return warnings;
}

// Bug 5 fix: strip extra BrowserRouter / HashRouter wrappers outside main.tsx
function stripExtraRouters(files: Record<string, string>): string[] {
  const warnings: string[] = [];
  const mainEntry = Object.keys(files).find((p) => ENTRY_FILE_PATTERN.test(p));

  for (const [fp, content] of Object.entries(files)) {
    if (fp === mainEntry) continue;
    if (!/\.(tsx?|jsx?)$/.test(fp)) continue;
    if (!content.includes('BrowserRouter') && !content.includes('HashRouter')) continue;

    let updated = content;

    // Remove BrowserRouter / HashRouter import
    updated = updated.replace(/import\s*\{[^}]*\b(BrowserRouter|HashRouter)\b[^}]*\}\s*from\s*['"]react-router-dom['"];?\r?\n?/g, (match) => {
      const symbols = match.match(/\{([^}]+)\}/)?.[1] || '';
      const remaining = symbols.split(',').map(s => s.trim()).filter(s => s && s !== 'BrowserRouter' && s !== 'HashRouter');
      return remaining.length > 0 ? `import { ${remaining.join(', ')} } from 'react-router-dom';\n` : '';
    });

    // Strip JSX tags <BrowserRouter>...</BrowserRouter> or <HashRouter>...</HashRouter>
    updated = updated.replace(/<BrowserRouter[^>]*>([\s\S]*?)<\/BrowserRouter>/g, '$1');
    updated = updated.replace(/<HashRouter[^>]*>([\s\S]*?)<\/HashRouter>/g, '$1');

    if (updated !== content) {
      files[fp] = updated;
      const msg = `stripExtraRouters: removed nested Router wrapper from ${fp} (BrowserRouter belongs in main.tsx only)`;
      console.warn(`[Coder] ${msg}`);
      warnings.push(msg);
    }
  }

  return warnings;
}

// Bug 4 fix: ensure entry point & guaranteed root path "/"
function ensureEntryPoint(files: Record<string, string>, architecture: any): string[] {
  const warnings: string[] = [];
  const pageFiles = Object.keys(files)
    .filter((p) => /\/pages\//.test(p) && /\.(tsx|jsx)$/.test(p))
    .sort();

  const hasCss = Object.keys(files).some((p) => p === 'src/index.css');
  if (!hasCss) {
    files['src/index.css'] = '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n';
  }

  const appFile = Object.keys(files).find((p) => /^src\/App\.(tsx|jsx)$/.test(p));

  if (appFile) {
    let appContent = files[appFile];
    const hasRootRoute = /<Route\s+[^>]*path=["']\/["']/i.test(appContent);
    if (!hasRootRoute && appContent.includes('<Routes>')) {
      const homePage = pageFiles.find((p) => /home|index|landing/i.test(p)) || pageFiles[0];
      if (homePage) {
        const componentName = homePage.split('/').pop()!.replace(/\.(tsx|jsx)$/, '');
        const importPath = './' + homePage.replace(/^src\//, '').replace(/\.(tsx|jsx)$/, '');
        if (!appContent.includes(importPath)) {
          appContent = `import ${componentName} from '${importPath}';\n` + appContent;
        }
        appContent = appContent.replace(
          /(<Routes>)/,
          `$1\n        <Route path="/" element={<${componentName} />} />`,
        );
        files[appFile] = appContent;
        const msg = `ensureEntryPoint: guaranteed root route path="/" for ${componentName} in App.tsx`;
        console.warn(`[Coder] ${msg}`);
        warnings.push(msg);
      }
    }
  }

  const hasEntry = Object.keys(files).some((path) => ENTRY_FILE_PATTERN.test(path));
  if (hasEntry) {
    ensureBrowserRouter(files, warnings);
    return warnings;
  }

  if (!appFile && pageFiles.length > 0) {
    const routeImports: string[] = [];
    const routeElements: string[] = [];

    const homePage = pageFiles.find((p) => /home|index|landing/i.test(p)) || pageFiles[0];
    const homeCompName = homePage.split('/').pop()!.replace(/\.(tsx|jsx)$/, '');

    routeElements.push(`      <Route path="/" element={<${homeCompName} />} />`);

    for (const pagePath of pageFiles) {
      const componentName = pagePath.split('/').pop()!.replace(/\.(tsx|jsx)$/, '');
      const importPath = './' + pagePath.replace(/^src\//, '').replace(/\.(tsx|jsx)$/, '');
      const cleanName = componentName.toLowerCase().replace(/page$/i, '').replace(/index/i, '');
      const routePath = cleanName ? '/' + cleanName : '/';
      routeImports.push(`import ${componentName} from '${importPath}';`);
      if (routePath !== '/') {
        routeElements.push(`      <Route path="${routePath}" element={<${componentName} />} />`);
      }
    }

    files['src/App.tsx'] = `import { Routes, Route } from 'react-router-dom';
${routeImports.join('\n')}

export default function App() {
  return (
    <Routes>
${routeElements.join('\n')}
    </Routes>
  );
}
`;

    files['src/main.tsx'] = `import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>,
);
`;
    const msg = `ensureEntryPoint: composed App.tsx with ${pageFiles.length} pages and BrowserRouter-wrapped main.tsx`;
    console.warn(`[Coder] ${msg}`);
    warnings.push(msg);
    return warnings;
  }

  const firstPage =
    architecture?.fileStructure?.find((f: any) => /\/pages\//.test(f.path) && /\.(tsx|jsx)$/.test(f.path))?.path ||
    pageFiles[0];

  const targetPath = appFile || firstPage;

  if (!targetPath) {
    console.warn('[Coder] Could not find any component to wire up as the entry point — skipping entry-point fallback');
    return warnings;
  }

  const importPath = './' + targetPath.replace(/^src\//, '').replace(/\.(tsx|jsx)$/, '');
  const componentName = targetPath.split('/').pop()!.replace(/\.(tsx|jsx)$/, '');

  const needsRouter = usesRouter(files);
  const routerImport = needsRouter ? `import { BrowserRouter } from 'react-router-dom';\n` : '';
  const routerOpen = needsRouter ? '    <BrowserRouter>\n      ' : '    ';
  const routerClose = needsRouter ? '\n    </BrowserRouter>' : '';

  files['src/main.tsx'] = `import React from 'react';
import ReactDOM from 'react-dom/client';
${routerImport}import ${componentName} from '${importPath}';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
${routerOpen}<${componentName} />${routerClose}
  </React.StrictMode>,
);
`;

  const fallbackMsg = `ensureEntryPoint: added fallback src/main.tsx (rendering ${componentName}${needsRouter ? ' with BrowserRouter' : ''})`;
  console.warn(`[Coder] ${fallbackMsg}`);
  warnings.push(fallbackMsg);
  return warnings;
}

function ensureBrowserRouter(files: Record<string, string>, warnings: string[] = []): void {
  const mainEntry = Object.keys(files).find((p) => ENTRY_FILE_PATTERN.test(p));
  if (!mainEntry) return;

  const mainContent = files[mainEntry];
  if (mainContent.includes('BrowserRouter') || mainContent.includes('HashRouter')) return;
  if (!usesRouter(files)) return;

  const withRouter = mainContent
    .replace(
      /import ReactDOM from ['"](react-dom\/client|react-dom)['"];/,
      `import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';`,
    )
    .replace(
      /(<React\.StrictMode>)(\s*)(<[A-Z][^/]*\/>)(\s*)(<\/React\.StrictMode>)/,
      `<React.StrictMode>\n    <BrowserRouter>\n      $3\n    </BrowserRouter>\n  </React.StrictMode>`,
    );

  if (withRouter !== mainContent) {
    files[mainEntry] = withRouter;
    const msg = `ensureBrowserRouter: wrapped existing ${mainEntry} render in <BrowserRouter>`;
    console.warn(`[Coder] ${msg}`);
    warnings.push(msg);
  }
}

// ── 1c: guaranteed stylesheet ─────────────────────────────────────────────────
function ensureStylesheet(files: Record<string, string>): void {
  const CSS_PATH = 'src/index.css';
  const TAILWIND_DIRECTIVES = '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n';

  if (!files[CSS_PATH]) {
    files[CSS_PATH] = TAILWIND_DIRECTIVES + '\nbody {\n  margin: 0;\n  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;\n}\n';
    console.log('[Coder] ensureStylesheet: created src/index.css with Tailwind directives');
  } else if (!files[CSS_PATH].includes('@tailwind')) {
    files[CSS_PATH] = TAILWIND_DIRECTIVES + '\n' + files[CSS_PATH];
    console.log('[Coder] ensureStylesheet: prepended Tailwind directives to existing src/index.css');
  }

  const mainEntry = Object.keys(files).find((p) => ENTRY_FILE_PATTERN.test(p));
  if (!mainEntry) return;

  const mainContent = files[mainEntry];
  if (/import\s+['\.](.*index|.*\/index)?\.(css|scss|sass)['"]/.test(mainContent)) return;
  if (mainContent.includes("'./index.css'") || mainContent.includes('"./index.css"')) return;

  files[mainEntry] = `import './index.css';\n` + mainContent;
  console.log(`[Coder] ensureStylesheet: injected CSS import into ${mainEntry}`);
}

// Bug 6 fix: ensure SharedLayout contract ({children ?? <Outlet />})
const LAYOUT_NAME_RE = /^src\/components\/(SharedLayout|AppLayout|Layout|Navbar|Navigation|NavBar|Header|AppShell)\.(tsx|jsx)$/i;

function ensureSharedLayout(files: Record<string, string>): string[] {
  const warnings: string[] = [];
  const layoutFile = Object.keys(files).find((p) => LAYOUT_NAME_RE.test(p));
  if (!layoutFile) return warnings;

  const layoutName = layoutFile.split('/').pop()!.replace(/\.(tsx|jsx)$/, '');

  let layoutContent = files[layoutFile];
  if (!layoutContent.includes('Outlet')) {
    if (!layoutContent.includes("from 'react-router-dom'")) {
      layoutContent = `import { Outlet } from 'react-router-dom';\n` + layoutContent;
    } else {
      layoutContent = layoutContent.replace(
        /import\s*\{([^}]+)\}\s*from\s*['"]react-router-dom['"]/,
        (m, syms) => `import { ${syms.trim()}, Outlet } from 'react-router-dom'`,
      );
    }
  }
  if (!layoutContent.includes('children') && !layoutContent.includes('<Outlet')) {
    layoutContent = layoutContent.replace(
      /(<main[^>]*>|<div[^>]*>)/,
      `$1\n      {children ?? <Outlet />}`,
    );
    files[layoutFile] = layoutContent;
    const msg = `ensureSharedLayout: made ${layoutName} render {children ?? <Outlet />}`;
    console.warn(`[Coder] ${msg}`);
    warnings.push(msg);
  }

  // Strip self-wrapping layout tags from individual page components
  for (const [fp, content] of Object.entries(files)) {
    if (fp === layoutFile) continue;
    if (!/\/pages\//.test(fp)) continue;
    if (!content.includes(layoutName)) continue;

    const wrapRegex = new RegExp(`<${layoutName}[^>]*>([\\s\\S]*?)<\\/${layoutName}>`, 'g');
    if (wrapRegex.test(content)) {
      files[fp] = content.replace(wrapRegex, '$1');
      const msg = `ensureSharedLayout: stripped self-wrapping <${layoutName}> from ${fp}`;
      console.warn(`[Coder] ${msg}`);
      warnings.push(msg);
    }
  }

  const appFile = Object.keys(files).find((p) => /^src\/App\.(tsx|jsx)$/.test(p));
  if (appFile) {
    const appContent = files[appFile];
    if (!appContent.includes(layoutName) && appContent.includes('<Routes>')) {
      const importPath = './' + layoutFile.replace(/^src\//, '').replace(/\.(tsx|jsx)$/, '');
      let newContent = appContent;
      if (!newContent.includes(importPath)) {
        newContent = `import ${layoutName} from '${importPath}';\n` + newContent;
      }
      newContent = newContent.replace(
        /(<Routes>[\s\S]*?<\/Routes>)/,
        `<${layoutName}>\n      $1\n    </${layoutName}>`,
      );
      if (newContent !== appContent) {
        files[appFile] = newContent;
        const msg = `ensureSharedLayout: wired ${layoutName} around <Routes> in App.tsx`;
        console.warn(`[Coder] ${msg}`);
        warnings.push(msg);
      }
    }
  }

  return warnings;
}

// Bug 7 & 8 fix: bare route paths, server port 3001, auth middleware stub, DB seed wiring
function fixBackendRoutesAndServer(files: Record<string, string>): string[] {
  const warnings: string[] = [];

  for (const [fp, content] of Object.entries(files)) {
    if (!/^(server|backend)\/routes\/[^\/]+\.js$/.test(fp)) continue;
    const moduleName = fp.split('/').pop()!.replace(/\.js$/, '').toLowerCase();

    const redundantPrefixRe = new RegExp(`(router\\.(?:get|post|put|delete|patch)\\s*\\(\\s*['"])\\/${moduleName}(\\/|['"])`, 'gi');
    if (redundantPrefixRe.test(content)) {
      const fixed = content.replace(redundantPrefixRe, '$1$2');
      files[fp] = fixed;
      const msg = `fixBackendRoutesAndServer: stripped redundant prefix "/${moduleName}" in ${fp} (routers use bare relative paths)`;
      console.warn(`[Coder] ${msg}`);
      warnings.push(msg);
    }
  }

  const serverEntry = Object.keys(files).find((p) => /^(server|backend)\/(index|server)\.js$/.test(p));
  if (serverEntry) {
    let serverContent = files[serverEntry];
    let changed = false;

    if (serverContent.includes('5000')) {
      serverContent = serverContent.replace(/\b5000\b/g, '3001');
      changed = true;
      const msg = `fixBackendRoutesAndServer: updated server port in ${serverEntry} to 3001 to match vite proxy`;
      console.warn(`[Coder] ${msg}`);
      warnings.push(msg);
    }

    const usesReqUser = Object.entries(files).some(([p, c]) => isBackendPath(p) && c.includes('req.user'));
    if (usesReqUser && !serverContent.includes('req.user')) {
      const authMiddleware = `\n// Injected stub authentication middleware\napp.use((req, res, next) => { req.user = req.user || { id: 1, email: 'demo@example.com' }; next(); });\n`;
      serverContent = serverContent.replace(/(const app = express\(\);|express\(\);)/, `$1\n${authMiddleware}`);
      changed = true;
      const msg = `fixBackendRoutesAndServer: injected stub auth middleware (req.user = { id: 1 }) into ${serverEntry}`;
      console.warn(`[Coder] ${msg}`);
      warnings.push(msg);
    }

    if (changed) {
      files[serverEntry] = serverContent;
    }
  }

  // Bug 8 fix: wire seed.js / seed.sql into DB initializer or server entry
  const seedFile = Object.keys(files).find((p) => /^(server|backend)\/(database\/)?seed\.(js|sql)$/.test(p));
  const dbInitFile = Object.keys(files).find((p) => /^(server|backend)\/(database\/)?db\.js$/.test(p));

  if (seedFile && dbInitFile) {
    let dbContent = files[dbInitFile];
    if (!dbContent.includes('seed.js') && !dbContent.includes('seed.sql')) {
      const isSqlSeed = seedFile.endsWith('.sql');
      const seedCode = isSqlSeed
        ? `\n    const SEED_PATH = join(__dir, '${seedFile.split('/').pop()}');\n    if (existsSync(SEED_PATH)) {\n      try { _db.run(readFileSync(SEED_PATH, 'utf8')); persistDb(); } catch (e) { console.warn('[DB] Seed warning:', e?.message); }\n    }\n`
        : `\n    const SEED_PATH = join(__dir, '${seedFile.split('/').pop()}');\n    if (existsSync(SEED_PATH)) {\n      try { const s = await import('./${seedFile.split('/').pop()}'); if (typeof s.seed === 'function') await s.seed(_db); else if (typeof s.default === 'function') await s.default(_db); } catch (e) { console.warn('[DB] Seed warning:', e?.message); }\n    }\n`;

      if (dbContent.includes('persistDb();')) {
        dbContent = dbContent.replace('persistDb();', `${seedCode}    persistDb();`);
      } else {
        dbContent += seedCode;
      }
      files[dbInitFile] = dbContent;
      const seedMsg = `fixBackendRoutesAndServer: wired ${seedFile} into ${dbInitFile} (runs once on empty DB)`;
      console.warn(`[Coder] ${seedMsg}`);
      warnings.push(seedMsg);
    }
  } else if (seedFile && serverEntry) {
    let serverContent = files[serverEntry];
    if (!serverContent.includes('seed.js') && !serverContent.includes('seed.sql')) {
      const seedName = seedFile.split('/').pop();
      const seedRunner = `\n// Injected: auto-run seed script on server startup if present\ntry {\n  const fs = require('fs'); const path = require('path');\n  const seedPath = path.join(__dirname, '${seedFile.includes('database/') ? 'database/' : ''}${seedName}');\n  if (fs.existsSync(seedPath)) require('./${seedFile.includes('database/') ? 'database/' : ''}${seedName}');\n} catch (e) { console.warn('[Server] Seed execution notice:', e?.message); }\n`;
      serverContent = serverContent + seedRunner;
      files[serverEntry] = serverContent;
      const seedMsg = `fixBackendRoutesAndServer: wired ${seedFile} into ${serverEntry} (runs once on startup)`;
      console.warn(`[Coder] ${seedMsg}`);
      warnings.push(seedMsg);
    }
  }

  return warnings;
}

// Bug 9 fix: cleanup duplicate HTML shells
function cleanupDuplicateHtmlFiles(files: Record<string, string>): string[] {
  const warnings: string[] = [];
  const htmlFiles = Object.keys(files).filter((p) => p.endsWith('.html'));

  for (const p of htmlFiles) {
    if (p !== 'index.html') {
      delete files[p];
      const msg = `cleanupDuplicateHtmlFiles: removed extra HTML shell at "${p}"`;
      console.warn(`[Coder] ${msg}`);
      warnings.push(msg);
    }
  }

  return warnings;
}

// ── Restored Helper Functions for Bug 1d & Bug 3 ──────────────────────────────
function validateSyntaxBalance(code: string, filePath: string): { valid: boolean; error?: string } {
  if (!/\.(tsx?|jsx?)$/.test(filePath)) return { valid: true };

  let braces = 0, parens = 0, brackets = 0;
  let inSingle = false, inDouble = false, inTemplate = 0;

  for (let i = 0; i < code.length; i++) {
    const ch = code[i];
    const prev = i > 0 ? code[i - 1] : '';

    if (!inSingle && !inDouble && inTemplate === 0 && ch === '`' && prev !== '\\') { inTemplate++; continue; }
    if (inTemplate > 0) { if (ch === '`' && prev !== '\\') inTemplate--; continue; }
    if (!inDouble && ch === "'" && prev !== '\\') { inSingle = !inSingle; continue; }
    if (!inSingle && ch === '"' && prev !== '\\') { inDouble = !inDouble; continue; }
    if (inSingle || inDouble) continue;

    if (ch === '{') braces++;
    else if (ch === '}') braces--;
    else if (ch === '(') parens++;
    else if (ch === ')') parens--;
    else if (ch === '[') brackets++;
    else if (ch === ']') brackets--;
  }

  if (braces !== 0) return { valid: false, error: `Unbalanced braces (net: ${braces > 0 ? '+' : ''}${braces})` };
  if (parens !== 0) return { valid: false, error: `Unbalanced parentheses (net: ${parens > 0 ? '+' : ''}${parens})` };
  if (brackets !== 0) return { valid: false, error: `Unbalanced brackets (net: ${brackets > 0 ? '+' : ''}${brackets})` };
  return { valid: true };
}

function resolveRelativeImport(fromFile: string, importPath: string): string {
  const parts = fromFile.split('/');
  parts.pop();
  for (const seg of importPath.split('/')) {
    if (seg === '..') parts.pop();
    else if (seg !== '.') parts.push(seg);
  }
  return parts.join('/');
}
// ─────────────────────────────────────────────────────────────────────────────

// Bug 3 fix: create functional component stubs for missing local imports
function createMissingImportStubs(files: Record<string, string>): string[] {
  const warnings: string[] = [];
  const IMPORT_RE = /^(?:import\s+(?:[\s\S]*?from\s+)?|export\s+\{[^}]*\}\s+from\s+)['"](\.[\/]?[^'"]+)['"]/gm;
  const REQUIRE_RE = /require\s*\(\s*['"](\.[^'"]+)['"]\s*\)/g;
  const TRY_EXTS = ['', '.ts', '.tsx', '.js', '.jsx', '/index.ts', '/index.tsx', '/index.js', '/index.jsx'];
  const stubs: Record<string, string> = {};

  for (const [filePath, content] of Object.entries(files)) {
    if (!/\.(tsx?|jsx?)$/.test(filePath)) continue;

    for (const re of [IMPORT_RE, REQUIRE_RE]) {
      re.lastIndex = 0;
      let m: RegExpExecArray | null;
      while ((m = re.exec(content)) !== null) {
        const importPath = m[1];
        const resolved = resolveRelativeImport(filePath, importPath);
        const exists = TRY_EXTS.some((ext) => (resolved + ext) in files || (resolved + ext) in stubs);
        if (exists) continue;

        const ext = resolved.includes('.') ? resolved.split('.').pop()! : '';
        const compName = (resolved.split('/').pop() || 'Placeholder').replace(/\.(tsx?|jsx?)$/, '');
        const targetPath = (ext === 'tsx' || ext === 'jsx' || !ext) ? (resolved.endsWith('.tsx') ? resolved : `${resolved}.tsx`) : resolved;

        if (ext === 'css' || ext === 'scss' || ext === 'sass') {
          stubs[targetPath] = '/* auto-generated stub */\n';
        } else if (ext === 'ts' || ext === 'js') {
          stubs[targetPath] = 'export {};\n';
        } else {
          stubs[targetPath] =
            `export default function ${compName}() {\n` +
            `  return (\n` +
            `    <div className="p-8">\n` +
            `      <h2 className="text-xl font-semibold">${compName}</h2>\n` +
            `      <p className="text-sm text-gray-500">This page has not been generated yet.</p>\n` +
            `    </div>\n` +
            `  );\n` +
            `}\n`;
        }
      }
    }
  }

  for (const [stubPath, content] of Object.entries(stubs)) {
    if (!(stubPath in files)) {
      files[stubPath] = content;
      const msg = `createMissingImportStubs: created functional stub component for missing import ${stubPath}`;
      console.warn(`[Coder] ⚠️ ${msg}`);
      warnings.push(msg);
    }
  }

  return warnings;
}

export class CoderAgent extends AgentBase {
  constructor(env?: Record<string, string>) {
    super({
      name: 'coder',
      maxRetries: 3,
      timeoutMs: 1200000,
    }, env);
  }

  async execute(input: AgentInput): Promise<AgentOutput> {
    const { requirements, architecture, designDecisions } = input.context || {};

    if (!requirements || !architecture) {
      throw new Error('Coder needs requirements and architecture first');
    }

    const fileList: Array<{ path: string; purpose: string }> = (architecture as any).fileStructure || [];

    let allGeneratedFiles: Record<string, string> = {};

    const plannedPkg = (() => {
      try { return JSON.parse(buildConfigFileTemplates(requirements, architecture)['package.json'] || '{}'); }
      catch { return {}; }
    })();
    const versionHints = buildVersionHintsBlock(plannedPkg);

    if (fileList.length > 0) {
      allGeneratedFiles = await this.generatePerFile(fileList, requirements, architecture, designDecisions, versionHints, input);
    } else {
      console.warn('[Coder] Architecture has no fileStructure — falling back to blob generation');
      allGeneratedFiles = await this.generateAsBlobsFallback(requirements, architecture, designDecisions);
    }

    const configTemplates = buildConfigFileTemplates(requirements, architecture);
    allGeneratedFiles = { ...allGeneratedFiles, ...configTemplates };

    if (typeof input.onProgress === 'function') {
      for (const [cp, cc] of Object.entries(configTemplates)) {
        input.onProgress({
          runId: input.runId || 0,
          agentName: 'coder',
          status: 'file_generated',
          message: `Generated ${cp}`,
          data: { filePath: cp, content: cc },
        });
      }
    }

    if (Object.keys(allGeneratedFiles).length === 0) {
      throw new Error('Coder generated zero files');
    }

    const dataFiles = (input.context as any)?.dataFiles?.dataFiles || {};
    const integrationFiles = (input.context as any)?.integrationData?.files || {};

    const allFiles = {
      ...allGeneratedFiles,
      ...dataFiles,
      ...integrationFiles,
    };

    // ── Bug 10: Master Consistency & Quality Passes ──────────────────────────
    const consistencyWarnings: string[] = [];

    // Bug 9: Clean up junk extra index.html files
    consistencyWarnings.push(...cleanupDuplicateHtmlFiles(allFiles));

    // Bug 5: Strip nested Router wrappers outside main.tsx
    consistencyWarnings.push(...stripExtraRouters(allFiles));

    // Bug 6: Ensure SharedLayout contract ({children ?? <Outlet />})
    consistencyWarnings.push(...ensureSharedLayout(allFiles));

    // Bug 4: Ensure entry point & guaranteed root path "/"
    consistencyWarnings.push(...ensureEntryPoint(allFiles, architecture));

    // Bug 7 & 8: Fix backend route paths, server port 3001, auth stub, DB seeding
    consistencyWarnings.push(...fixBackendRoutesAndServer(allFiles));

    // Bug 1b: React compat guard (react-data-grid vs React 18)
    guardReactCompatibility(allFiles);

    // Bug 1: Reconcile dependencies & validate imports
    consistencyWarnings.push(...reconcileDependencies(allFiles));

    // Bug 1c: Guarantee stylesheet + index.css import
    ensureStylesheet(allFiles);

    // Bug 3: Create functional stubs for missing local imports
    consistencyWarnings.push(...createMissingImportStubs(allFiles));

    console.log(`[Coder] Total files generated: ${Object.keys(allFiles).length}`);
    Object.keys(allFiles).forEach((f) => console.log(`  → ${f}`));

    // ── Part 2: build self-healing loop (Node.js only, skipped on Workers) ───
    const healResult = await runBuildHeal(allFiles, this.callLLM.bind(this));
    const healedFiles = healResult.files;

    const allBuildWarnings = [
      ...consistencyWarnings,
      ...healResult.buildWarnings,
    ];

    if (allBuildWarnings.length > 0) {
      allBuildWarnings.forEach((w) => console.warn(`[Coder Quality] ⚠️ ${w}`));
    }

    return {
      success: true,
      agentName: 'coder',
      data: healedFiles,
      ...(allBuildWarnings.length > 0 ? { warnings: allBuildWarnings } : {}),
    };
  }

  // ── Part 1d: generate one file safely with syntax validation + retry ────────
  private async generateSingleFileSafe(
    systemPrompt: string,
    userPromptFn: () => string,
    filePath: string,
  ): Promise<string | null> {
    const MAX_RETRIES = 2;

    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
      let code: string;
      try {
        const isRetry = attempt > 0;
        const prompt = isRetry
          ? `The previous response for "${filePath}" had a syntax error (unbalanced braces/parens/brackets). ` +
            `Rewrite the COMPLETE file from scratch.\n` +
            `IMPORTANT: Define all object/array constants as separate const variables ABOVE the component — ` +
            `never inline complex objects as JSX prop values. Ensure all {}, (), [] are perfectly balanced.\n\n` +
            userPromptFn()
          : userPromptFn();

        const raw = await this.callLLM(systemPrompt, prompt, false, PER_FILE_TIMEOUT_MS);
        code = this.stripCodeFence(raw);
      } catch (err: any) {
        console.error(`[Coder] ⚠️ LLM call failed for ${filePath} (attempt ${attempt + 1}/${MAX_RETRIES + 1}): ${err.message}`);
        if (attempt === MAX_RETRIES) return null;
        continue;
      }

      const check = validateSyntaxBalance(code, filePath);
      if (check.valid) return code;

      console.warn(`[Coder] ⚠️ Syntax imbalance in ${filePath} (attempt ${attempt + 1}/${MAX_RETRIES + 1}): ${check.error}`);
      if (attempt === MAX_RETRIES) {
        console.error(`[Coder] ❌ ${filePath} still has syntax issues after ${MAX_RETRIES} retries — using placeholder stub`);
        return null;
      }
    }
    return null;
  }

  private createPlaceholderStub(filePath: string, purpose: string): string {
    const ext = (filePath.split('.').pop() || '').toLowerCase();
    if (ext === 'css' || ext === 'scss') return `/* Placeholder: ${purpose} — generation failed */\n`;
    if (ext === 'sql') return `-- Placeholder: ${purpose} — generation failed\n`;
    const name = (filePath.split('/').pop() || 'Component').replace(/\.(tsx?|jsx?)$/, '');
    return (
      `// ⚠️ Placeholder: ${purpose} — generation failed after retries\n` +
      `export default function ${name}() {\n` +
      `  return <div style={{padding:16,color:'red'}}>⚠️ ${name} could not be generated</div>;\n` +
      `}\n`
    );
  }

  private async generatePerFile(
    fileList: Array<{ path: string; purpose: string }>,
    requirements: any,
    architecture: any,
    designDecisions: any,
    versionHints?: string,
    input?: AgentInput,
  ): Promise<Record<string, string>> {
    const files: Record<string, string> = {};
    const failed: string[] = [];
    const existingFiles = input?.context?.existingFiles || {};
    const onProgress = input?.onProgress;
    const runId = input?.runId || 0;

    const frontendFiles = fileList.filter((f) => !isBackendPath(f.path) && !isConfigFile(f.path));
    const backendFiles = fileList.filter((f) => isBackendPath(f.path) && !isConfigFile(f.path));
    const skippedConfigCount = fileList.length - frontendFiles.length - backendFiles.length;

    console.log(
      `[Coder] Generating ${frontendFiles.length} frontend file(s) and ${backendFiles.length} backend/database file(s), one call each` +
        (skippedConfigCount > 0 ? ` (${skippedConfigCount} config file(s) handled by template, no LLM call needed)` : '') +
        '...',
    );

    const notifyFile = (filePath: string, content: string) => {
      if (typeof onProgress === 'function') {
        onProgress({
          runId,
          agentName: 'coder',
          status: 'file_generated',
          message: `Generated ${filePath}`,
          data: { filePath, content },
        });
      }
    };

    const isExistingFileValid = (content: string): boolean => {
      if (!content || typeof content !== 'string') return false;
      if (content.includes('⚠️ Placeholder') || content.includes('generation failed after retries')) return false;
      return content.trim().length > 10;
    };

    for (const file of frontendFiles) {
      if (existingFiles[file.path] && isExistingFileValid(existingFiles[file.path])) {
        console.log(`[Coder] ⏩ Reusing already generated file for ${file.path}`);
        files[file.path] = existingFiles[file.path];
        notifyFile(file.path, files[file.path]);
        continue;
      }

      console.log(`[Coder] → ${file.path}`);
      const code = await this.generateSingleFileSafe(
        FRONTEND_FILE_SYSTEM_PROMPT,
        () => FRONTEND_FILE_USER_PROMPT(requirements, architecture, designDecisions, file.path, file.purpose, versionHints),
        file.path,
      );
      if (code !== null) {
        files[file.path] = code;
      } else {
        files[file.path] = this.createPlaceholderStub(file.path, file.purpose);
        failed.push(file.path);
      }
      notifyFile(file.path, files[file.path]);
    }

    for (const file of backendFiles) {
      if (existingFiles[file.path] && isExistingFileValid(existingFiles[file.path])) {
        console.log(`[Coder] ⏩ Reusing already generated file for ${file.path}`);
        files[file.path] = existingFiles[file.path];
        notifyFile(file.path, files[file.path]);
        continue;
      }

      console.log(`[Coder] → ${file.path}`);
      const code = await this.generateSingleFileSafe(
        BACKEND_FILE_SYSTEM_PROMPT,
        () => BACKEND_FILE_USER_PROMPT(architecture, file.path, file.purpose, versionHints),
        file.path,
      );
      if (code !== null) {
        files[file.path] = code;
      } else {
        files[file.path] = this.createPlaceholderStub(file.path, file.purpose);
        failed.push(file.path);
      }
      notifyFile(file.path, files[file.path]);
    }

    if (failed.length > 0) {
      console.warn(`[Coder] ${failed.length} file(s) fell back to stub after retries: ${failed.join(', ')}`);
    }

    return files;
  }

  private async generateAsBlobsFallback(
    requirements: any,
    architecture: any,
    designDecisions: any,
  ): Promise<Record<string, string>> {
    const frontendJson = await this.callLLM(
      FRONTEND_CODER_SYSTEM_PROMPT,
      FRONTEND_CODER_USER_PROMPT(requirements, architecture, designDecisions),
      true,
    );
    const frontendResult = this.parseJson<{ files: Record<string, string> }>(frontendJson);

    let backendFiles: Record<string, string> = {};
    const needsBackend =
      (architecture.apiRoutes && architecture.apiRoutes.length > 0) ||
      (architecture.databaseSchema && architecture.databaseSchema.length > 0);

    if (needsBackend) {
      try {
        const backendJson = await this.callLLM(
          BACKEND_CODER_SYSTEM_PROMPT,
          BACKEND_CODER_USER_PROMPT(architecture),
          true,
        );
        const backendResult = this.parseJson<{ files: Record<string, string> }>(backendJson);
        backendFiles = backendResult.files || {};
      } catch (error: any) {
        console.error('[Coder] Backend generation failed, continuing with frontend only:', error.message);
      }
    }

    return {
      ...this.sanitizeFileMap(frontendResult.files),
      ...this.sanitizeFileMap(backendFiles),
    };
  }
}
